# Generated by Django 6.0.2 on 2026-02-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchaseorderline_basic_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='basic_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='total_amount',
        ),
    ]
