# Generated by Django 6.0.2 on 2026-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
