# Generated by Django 6.0.2 on 2026-02-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_purchaseorderline_igst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
    ]
