# Generated by Django 6.0.2 on 2026-02-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('print_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_type', models.CharField(choices=[('FG', 'Finished Goods'), ('SFG', 'Semi-Finished Goods'), ('RM', 'Raw Materials'), ('CN', 'Consumables'), ('HW', 'Hardware'), ('OTH', 'Others')], max_length=20)),
                ('bom_required', models.BooleanField(default=False)),
                ('supply_type', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_code', models.CharField(max_length=8, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='fullform',
            field=models.CharField(default='numbers', max_length=100),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='unit',
            field=models.CharField(default='nos', max_length=10),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.category'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='hsncode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.hsncode'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.uommaster'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='saccode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.saccode'),
        ),
    ]
