# Generated by Django 6.0.2 on 2026-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_itemmaster_saccode_stocklocation_delete_itemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uommaster',
            name='fullform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
