# Generated by Django 6.0.2 on 2026-02-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_uommaster_fullform_alter_uommaster_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saccode',
            name='sac_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
