# Generated by Django 6.0.2 on 2026-02-12 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_saccode_sac_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsncode',
            name='hsn_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='HSN code must be of 8 digits.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='saccode',
            name='sac_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='SAC code must be of 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
