# Generated by Django 6.0.2 on 2026-02-12 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_hsncode_hsn_code_alter_saccode_sac_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsncode',
            name='hsn_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='HSN code must be of 2,4,6,8 digits.', regex='^(\\d{2}|\\d{4}|\\d{6}|\\d{8})$')]),
        ),
    ]
