# Generated by Django 6.0.2 on 2026-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_hsncode_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='item_type',
            field=models.CharField(choices=[('Finished Goods', 'FG'), ('Semi-Finished Goods', 'SFG'), ('Raw Materials', 'RM'), ('Consumables', 'CN'), ('Hardware', 'HW'), ('Others', 'OTH')], max_length=20),
        ),
    ]
