# Generated by Django 6.0.2 on 2026-02-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_itemmaster_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
