# Generated by Django 6.0.2 on 2026-02-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_itemmaster_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='item_type',
            field=models.CharField(choices=[('FG', 'FG'), ('SFG', 'SFG'), ('RM', 'RM'), ('CN', 'CN'), ('HW', 'HW'), ('OTH', 'OTH')], max_length=20),
        ),
    ]
