# Generated by Django 6.0.2 on 2026-02-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_alter_itemmaster_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=100, null=True)),
                ('GST_No', models.CharField(max_length=15, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('IT_Pan_No', models.CharField(max_length=10, null=True)),
                ('Account_category', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Bank', 'Bank'), ('Cash', 'Cash'), ('Capital', 'Capital'), ('Fixed Asset', 'Fixed Asset')], max_length=20)),
                ('Bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('AC_No', models.CharField(blank=True, max_length=200, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=200, null=True)),
                ('Branch_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
