# Generated by Django 6.0.2 on 2026-02-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_accountmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
