# Generated by Django 6.0.2 on 2026-02-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_accountmaster_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountmaster',
            name='GST_No',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountmaster',
            name='ledger_name',
            field=models.CharField(default=' ', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='accountmaster',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.statemaster'),
        ),
    ]
