# Generated by Django 6.0.2 on 2026-02-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_statemaster_accountmaster_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmaster',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.state'),
        ),
        migrations.DeleteModel(
            name='StateMaster',
        ),
    ]
