# Generated by Django 6.0.2 on 2026-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myErp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uommaster',
            name='fullform',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='unit',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
