# Generated by Django 6.0.2 on 2026-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myErp', '0003_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSNcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=8, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='fullform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
