# Generated by Django 6.0.2 on 2026-02-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myErp', '0004_hsncode_alter_state_state_alter_uommaster_fullform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=2, unique=True)),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
