# Generated by Django 6.0.2 on 2026-02-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myErp', '0005_itemtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HSNcode',
        ),
        migrations.DeleteModel(
            name='itemType',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='UOMmaster',
        ),
    ]
